language: haskell
ghc:
  - "7.8"
  - "7.10"
install:
  - "cabal install --only-dependencies --enable-tests"
script:
  - "cabal configure --enable-tests && cabal build && cabal test"

notifications:
  email: true
